### ISSUE TITLE
Broken logo on landing page

### ISSUE THREAD

**Issue by AlexanderTitus** [Synthome-ai/synthome.ai#7]
<img width="771" alt="Screenshot 2024-07-02 at 08 44 11" src="https://github.com/Synthome-ai/synthome.ai/assets/15268064/6b93589c-f128-43ca-b88f-543e4c6959e8">

**Comment by samadon1** [comment]
Got it. on it

**Comment by AlexanderTitus** [comment]
Just gave you write access instead of requiring PR.

Cheers,
-Titus

*-- -- -- -- -- -- -- -- -- -- --*
EA: Chelsea Coyomani
Email: ***@***.***

*"*Ad Astra Per Alia Porci - to the stars on the wings of a pig" *-John
Steinbeck*

**Comment by samadon1** [comment]
Thanks

**Comment by samadon1** [comment]
fixed ✅
